#!/usr/bin/with-contenv bash

_term() {
  echo "Caught SIGTERM signal!"
  kill -TERM "$(cat /run/hostapd.pid)" 2>/dev/null
}

        trap _term SIGTERM

        s6-setuidgid abc /usr/sbin/hostapd -P /run/hostapd.pid -i ${PRIV_INT} /etc/hostapd/hostapd.conf &

        wait
