#!/usr/bin/with-contenv bash
# shellcheck shell=bash
_term() {
  echo "Caught SIGTERM signal!"
  /etc/init.d/hapwizard stop
}

trap _term SIGTERM

# shellcheck disable=SC1091
/etc/init.d/hapwizard start

"$(dirname "${BASH_SOURCE[0]}")/health-check" &
# until all background processes finish or SIGTERM
wait
