version: '2'
services:
  zigbee2mqtt:
    hostname: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - data:/app/data
      - udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
      - ZIGBEE2MQTT_DATA=./data
    devices:
      # Make sure this matched your adapter location in app/data/configuration.yaml
      - /dev/ttyS0
  homeassistant:
    hostname: homeassistant.local
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - config:/config
      - localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  homebridge:
    hostname: homebridge.local
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    ports:
      - 8581:8581
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    volumes:
      - homebridge:/homebridge
  wifi-spot:
    network_mode: host
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.aarch64
    image: betothreeprod/huewizpi-raspberrypi3-64
    env_file:
      - common.env
      - .env
    privileged: true
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.kernel-modules: "1"
      io.balena.features.firmware: "1"
    volumes:
      - hostapd:/etc/hostapd
      - hapwizard:/etc/hapwizard
      - wifi-connect:/usr/src/python-wifi-connect/
      - netplan:/etc/netplan
    depends_on:
      - wifi-box
    cap_add:
      - ALL
  wifi-box:
    network_mode: host
    build:
      context: ./python-wifi-connect
      dockerfile: Dockerfile.aarch64
    image: betothreeprod/python-wifi-connect-raspberrypi3-64
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.supervisor-api: "1"
    privileged: true
    ports:
      - 80:80
    volumes:
      - wifi-connect:/usr/src/app/
volumes:
  hostapd:
  hapwizard:
  wifi-connect:
  netplan:
  homebridge:
  udev:
  data:
  config:
  localtime:
