version: '2'
services:
  raspbee-deconz-hue:
    image: deconzcommunity/deconz:latest
    container_name: deconz
    restart: unless-stopped
    network_mode: host
    privileged: true
    group_add:
      - dialout
    ports:
      - 80:80
      - 443:443
    volumes:
      - deconz:/opt/deCONZ
      - localtime:/etc/localtime
    devices:
      - /dev/ttyAMA0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - DEBUG_HTTP=0
      - DECONZ_DEVICE=/dev/ttyAMA0   # This is the USB device that Raspbee/Conbee II is running on.
      - DECONZ_START_VERBOSE=1
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: hass
    volumes:
      - config:/config
      - localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyAMA0
  wifi-spot:
    container_name: hwzpi
    network_mode: host
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.aarch64
    image: betothreeprod/huewizpi-raspberrypi3-64
    env_file:
      - common.env
      - .env
    privileged: true
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.kernel-modules: "1"
      io.balena.features.firmware: "1"
    volumes:
      - hostapd:/etc/hostapd
      - hapwizard:/etc/hapwizard
      - netplan:/etc/netplan
    cap_add:
      - ALL
volumes:
  hostapd:
  hapwizard:
  netplan:
  config:
  localtime:
