#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides:          HAP Wizard
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Hostapd Wizard Service
# Description:       Intended to start a Hotspot Access point  on system startup.
### END INIT INFO

set -eu

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
SVC_NAME=hapwizard
DAEMON_CF="/etc/$SVC_NAME/$SVC_NAME.conf"
DAEMON_SVC="/usr/lib/systemd/system/$SVC_NAME.service.d/"
# shellcheck disable=SC1091
. /lib/lsb/init-functions

[ -f $DAEMON_CF ] || mkdir -p "$(dirname $DAEMON_CF)"
[ -f $DAEMON_CF ] || touch "$DAEMON_CF"
[ -d $DAEMON_SVC ] || mkdir -p "$DAEMON_SVC"

banner=("" "[services.d] $DAEMON_SVC" ""); log_daemon_msg "%s\n" "${banner[@]}"

DAEMON_CF="$DAEMON_CF $(find "$DAEMON_SVC" -name "*.conf")"
for cnf in $DAEMON_CF; do
  # shellcheck disable=SC1090
  . "$cnf"
done
[ -z "${scriptsd:-}" ] && scriptsd="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage=("" \
"Usage: $0 {start|stop|status|restart|fore-reload|install|uninstall}" \
"" \
"Definition: Intended to start a Hotspot Access point on system startup." \
"")

function list_phy_net() {
  filter="state UP"
  [ "$#" -gt 0 ] && filter=$1
  # list physical network ip
  ip link show | grep "$filter" | grep qlen | awk '{ print $2 }' | cut -d: -f1 | xargs
}
function install() {
  if [ -f /etc/init.d/networking ]; then
    :
  else
    systemctl unmask "netplan-wpa-${PRIV_INT}.service"
    systemctl daemon-reload
    systemctl enable "netplan-wpa-${PRIV_INT}.service"
  fi
  list_phy_net "state"
  sleep 2
  if [ -z "${CLIENT:-''}" ]; then
    if ! systemctl enable hostapd isc-dhcp-server; then
      systemctl enable dnsmasq
    else
      systemctl enable systemd-resolved isc-dhcp-server6
    fi
  fi
}
function start() {
  list_phy_net
  if [ -f /etc/init.d/networking ]; then
    # /etc/init.d/networking restart
    nmcli networking off
    sleep 2
    nmcli networking on
  else
    systemctl unmask "netplan-wpa-${PRIV_INT}.service"
    systemctl daemon-reload
    netplan apply
    systemctl start "netplan-wpa-${PRIV_INT}.service"
    dhclient -r "${WAN_INT}"
    dhclient "${WAN_INT}"
  fi
  list_phy_net "state"
  sleep 2
  if [ -z "${CLIENT:-''}" ]; then
    if ! systemctl start hostapd isc-dhcp-server; then
      systemctl start dnsmasq
    else
      systemctl start systemd-resolved isc-dhcp-server6
    fi
  fi
}
function stop() {
  if ! systemctl stop hostapd isc-dhcp-server; then
    systemctl stop dnsmasq
  else
    systemctl stop isc-dhcp-server6 systemd-resolved
  fi
}
function uninstall() {
  if ! systemctl disable hostapd isc-dhcp-server; then
    systemctl disable dnsmasq
  else
    systemctl disable isc-dhcp-server6 systemd-resolved
  fi
}
case "$1" in
    install)
        log_daemon_msg "${BASH_SOURCE[0]} Will be enabled..."
        install
        ;;
    uninstall)
        log_daemon_msg "${BASH_SOURCE[0]} Will be disabled..."
        uninstall
        ;;
    start)
        log_daemon_msg "${BASH_SOURCE[0]} Will be started..."
        start
        ;;
    stop)
        log_daemon_msg "${BASH_SOURCE[0]} Will be stopped now..."
        stop
        ;;
    restart|force-reload)
        $0 stop
        sleep 8
        $0 start
        ;;
    foreground)
        log_daemon_msg "${BASH_SOURCE[0]} Read tcpdump of Hotspot Acces Point."
        tcpdump -v -i "${PRIV_INT}"
        ;;
    *)
        log_daemon_msg "${usage[@]}" >&2
        exit 3
        ;;
esac
exit 0
