#!/usr/bin/with-contenv bash
# shellcheck shell=bash
_term() {
  echo "Caught SIGTERM signal!"
  /etc/init.d/hapwizard stop
}

trap _term SIGTERM

/etc/init.d/hapwizard install \
&& /etc/init.d/hapwizard start

# s6-setuidgid abc /etc/init.d/hapwizard foreground &
/etc/init.d/hapwizard foreground &

wait
