apiVersion: v1
kind: Service
metadata:
  annotations:
    io.balena.features.dbus: "1"
    io.balena.features.supervisor-api: "1"
    kompose.cmd: kompose convert --controller deployment -o kubernetes/armhf/ -f docker-compose.armhf
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: wifi-box
  name: wifi-box
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: wifi-box
status:
  loadBalancer: {}
