apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    io.balena.features.dbus: "1"
    io.balena.features.supervisor-api: "1"
    kompose.cmd: kompose convert --controller deployment -o kubernetes/armhf/ -f docker-compose.armhf
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: wifi-box
  name: wifi-box
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wifi-box
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        io.balena.features.dbus: "1"
        io.balena.features.supervisor-api: "1"
        kompose.cmd: kompose convert --controller deployment -o kubernetes/armhf/
          -f docker-compose.armhf
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: wifi-box
    spec:
      containers:
      - image: betothreeprod/python-wifi-connect-raspberrypi3
        imagePullPolicy: ""
        name: wifi-box
        ports:
        - containerPort: 80
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /usr/src/app/
          name: wifi-connect
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: wifi-connect
        persistentVolumeClaim:
          claimName: wifi-connect
status: {}
